dist: focal
language: php
php:
- '7.4'
- '8.0'
install:
- composer install
script:
- "composer validate"
- "./vendor/bin/phpunit"
- "./vendor/bin/phpcs ."
- SKIP_CURL=1 ./vendor/bin/phpunit
env:
  global:
    secure: E6Jl3i/IeWT3LsqUt48V8hv/m+oRsLQaw5Sls014H40D3o/AZueCFSVcXygrgn/OuKpcLii+9JXOoPyOCcNizgYPnTesOnJPBDDNZpFNunJOIieBNvpr/kryeu90RCJkNl9ejx0yCpzyrHeMWU1rfeyV3fbjc7AHWxKqVPphyIQ=
notifications:
  slack:
    secure: Y9/gIt06LC8CiuZ4WtiL1/n9yvkXK79zj4O8oe/+/lHasKnaowVUpEMeo0/rin+fRzHm0SVv7EbbpZD6g6yQvuS6+Hd+ZlaFGWj/r1qUEdk9ZIjD6GYprE62D+T7BX+dzh5wNBXXfi7S1dOX377oZ83gNOZy+5Qqee+dYOVtcm8=
